const filesName = [
  { content: 'App Store' },
  { content: 'FontExplorer X' },
  { content: 'Newsstand' },
  { content: 'Applicons' },
  { content: 'Game Center alt2' },
  { content: 'Notes' },
  { content: 'Burnable' },
  { content: 'Game Center alt3' },
  { content: 'Passbook' },
  { content: 'Calculator' },
  { content: 'Game Center alt4' },
  { content: 'Phone' },
  { content: 'Calendar - Blank' },
  { content: 'Gemini' },
  { content: 'Photos' },
  { content: 'Calendar Official' },
  { content: 'Idea Stuff 2' },
  { content: 'Photoshop' },
  { content: 'Calendar' },
  { content: 'Idea Stuff' },
  { content: 'Preview' },
  { content: 'Camera' },
  { content: 'Illustrator' },
  { content: 'Reminders' },
  { content: 'CandyBar' },
  { content: 'InDesign' },
  { content: 'RSS Notifier' },
  { content: 'Clock' },
  { content: 'Internal' },
  { content: 'Safari' },
  { content: 'CloudApp' },
  { content: 'iTunes Store' },
  { content: 'Settings' },
  { content: 'Cobook' },
  { content: 'LaCie FA Porsche 2' },
  { content: 'Smart' },
  { content: 'Compass' },
  { content: 'LaCie FA Porsche' },
  { content: 'Stocks' },
  { content: 'Contacts' },
  { content: 'LaCie Neil Poulton' },
  { content: 'System' },
  { content: 'Design Briefs' },
  { content: 'LaCie Rugged 2' },
  { content: 'Time Machine Disk' },
  { content: 'Developer' },
  { content: 'LaCie Rugged' },
  { content: 'Time Machine' },
  { content: 'Dictionary' },
  { content: 'Library' },
  { content: 'Trash Empty' },
  { content: 'Doo' },
  { content: 'Mail' },
  { content: 'Trash Full' },
  { content: 'Downloads' },
  { content: 'Maps' },
  { content: 'Trash Managed' },
  { content: 'Drop Stuff' },
  { content: 'Messages' },
  { content: 'Twitter' },
  { content: 'EasyFind' },
  { content: 'Misc Designs 01' },
  { content: 'Users' },
  { content: 'FaceTime' },
  { content: 'Monosnap' },
  { content: 'Videos' },
  { content: 'Finder' },
  { content: 'Music' },
  { content: 'Weather' },
];

export default filesName;
module.exports = filesName;
